// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0W9wSuCtUpeXdgoiD83UpsvZKk2IBlms',
    appId: '1:352695354014:web:f7c01ba346aafd5ab8b18f',
    messagingSenderId: '352695354014',
    projectId: 'mybudget-2c631',
    authDomain: 'mybudget-2c631.firebaseapp.com',
    storageBucket: 'mybudget-2c631.firebasestorage.app',
    measurementId: 'G-PSTMCKLKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcbKxmEfeF6GVyifY55nFzXBK-nnK7ufg',
    appId: '1:352695354014:android:80783af0e4abaf6fb8b18f',
    messagingSenderId: '352695354014',
    projectId: 'mybudget-2c631',
    storageBucket: 'mybudget-2c631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtj283EUmE0uetRRTA6tDVW4A6gS_D_zo',
    appId: '1:352695354014:ios:75253eee7233cab2b8b18f',
    messagingSenderId: '352695354014',
    projectId: 'mybudget-2c631',
    storageBucket: 'mybudget-2c631.firebasestorage.app',
    iosClientId: '352695354014-gnpkr2p1m4jlgih9j0laiknif2rmc6k8.apps.googleusercontent.com',
    iosBundleId: 'esisa.ac.ma.stockFlutter',
  );
}
